// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/wallet": {
            "post": {
                "description": "Validates the incoming payload and creates a new wallet associated with a phone number.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallet"
                ],
                "summary": "Create a new wallet",
                "parameters": [
                    {
                        "description": "Create Wallet Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wallet.CreateWalletRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Wallet created successfully",
                        "schema": {
                            "$ref": "#/definitions/wallet.CreateWalletResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid payload or data)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict (Duplicate phone number)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/wallet/balance": {
            "patch": {
                "description": "Directly updates the balance of a wallet based on the requested amount.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallet"
                ],
                "summary": "Modify wallet balance",
                "parameters": [
                    {
                        "description": "Update Balance Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wallet.UpdateWalletBalanceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Balance updated successfully",
                        "schema": {
                            "$ref": "#/definitions/wallet.UpdateWalletBalanceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid payload, insufficient balance, or capacity limit)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Wallet Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/wallet/phone/{phone_number}": {
            "get": {
                "description": "Fetches the wallet details using the provided phone number query parameter.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallet"
                ],
                "summary": "Retrieve a wallet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Phone number",
                        "name": "phone_number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Wallet retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/wallet.GetWalletResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid phone number format)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Wallet Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/wallet/{wallet_id}": {
            "get": {
                "description": "Fetches the wallet details using the provided phone number query parameter.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallet"
                ],
                "summary": "Retrieve a wallet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet ID",
                        "name": "wallet_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Wallet retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/wallet.GetWalletResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request (Invalid wallet ID format)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Wallet Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "wallet.CreateWalletRequest": {
            "type": "object",
            "properties": {
                "currency_code": {
                    "type": "string"
                },
                "family_id": {
                    "description": "a pointer because it can be null if the wallet is not part of a family",
                    "type": "string"
                },
                "national_id": {
                    "type": "string"
                },
                "owner_name": {
                    "description": "since they are 3 fields only i will not use a validation library",
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                }
            }
        },
        "wallet.CreateWalletResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "description": "the client will not know how to handle an ObjectID so i will handle it by .HEX()",
                    "type": "integer"
                },
                "created_at": {
                    "description": "time stamps",
                    "type": "string"
                },
                "wallet_id": {
                    "description": "note that this is a string and not an ObjectID because",
                    "type": "string"
                }
            }
        },
        "wallet.GetWalletResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "integer"
                },
                "birth_date": {
                    "type": "string"
                },
                "currency_code": {
                    "type": "string"
                },
                "family_id": {
                    "type": "string"
                },
                "national_id": {
                    "type": "string"
                },
                "owner_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "wallet_id": {
                    "type": "string"
                }
            }
        },
        "wallet.UpdateWalletBalanceRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "this can be positive or negative depending on the operation",
                    "type": "integer"
                },
                "phone_number": {
                    "type": "string"
                }
            }
        },
        "wallet.UpdateWalletBalanceResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "integer"
                },
                "updated_at": {
                    "description": "currency code will be added in the future",
                    "type": "string"
                },
                "wallet_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Wallet Service API",
	Description:      "This microservice handles wallets.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
